#! /usr/bin/perl
# Procedure: demo5
# Last update: 25/05/2009
#############################################################################
# IGSuite 4.0.0 - Provides an Office Suite by  simple web interface         #
# Copyright (C) 2002 Dante Ortolani  [LucaS]                                #
#                                                                           #
# This program is free software; you can redistribute it and/or             #
# modify it under the terms of the GNU General Public License               #
# as published by the Free Software Foundation; either version 2            #
# of the License, or (at your option) any later version.                    #
#                                                                           #
# This program is distributed in the hope that it will be useful,           #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with this program; if not, write to the Free Software Foundation,   #
# Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.           #
#############################################################################

use strict;
use IG;
IG::MkEnv(__PACKAGE__);

## Only an IG user can access to this demo
IG::DTable ( default_action => sub { $IG::demo_version || CheckPrivilege() } );

###########################################################################
###########################################################################
sub default_action
 {
  push @IG::errmsg, "Questa e' una demo! niente verra' inviato." if $on{text};

  HtmlHead();

  TaskHead( title => 'IG Framework Demo - Extended TextArea',
            width=>550);

  TaskMsg("Nel framework di IGSuite ogni strumento del web tipo
una normale textarea e' potenziato da feature accessorie. Nel caso dei
campi textarea ci sono molteplici feature (Ajax) identificate dalle piccole icone
sotto il campo.",5 );

  FormHead( name => 'test');

  Input( type             => 'textarea',
         name             => 'text',
         fieldstyle       => 'margin-top:15px;',
         style            => 'width:530px; height:300px;',
         fckeditor_width  => 530,
         fckeditor_height => 300,
         value            => 'vuoi vedere?? provva a cliccare sulle icone!',
         fckeditor        => 'optional');

  Input( type       => 'submit',
         float      => 'right' );
         
  FormFoot();
  
  TaskFoot();
  HtmlFoot();
 }
